plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version "${forge_gradle_version}"
    id 'com.gradleup.shadow' version "${shadow_version}"
}

version = mod_stage != "" ? "${mc_version}-${mod_version}-${mod_stage}" : "${mc_version}-${mod_version}"
group = mod_group
base.archivesName = mod_name

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

minecraft {
    mappings channel: "${mappings_channel}", version: "${mappings_version}"

    accessTransformer = 'src/main/resources/META-INF/accesstransformer.cfg'

    runs {
        client {
            taskName "runClient ${mod_name} ${mc_version}"
            environment 'MC_VERSION', "${mc_version}"
            property 'fml.coreMods.load', "${mod_plugin_class}"
        }

        server {
            taskName "runServer ${mod_name} ${mc_version}"
            environment 'MC_VERSION', "${mc_version}"
            property 'fml.coreMods.load', "${mod_plugin_class}"
        }
    }
}

configurations {
    bundled
    implementation.extendsFrom(bundled)

    buildDependencies
}

repositories {
    flatDir { dirs 'libs' }

    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${mc_version}-${forge_version}"
    bundled 'io.github.meldexun:asmutil:2.8.1'
    bundled 'io.github.meldexun:reflectionutil:1.0.0'
    bundled 'io.github.meldexun:memoryutil:1.1.0'
    bundled 'io.github.meldexun:imageutil:1.0.0'

    buildDependencies 'curse.maven:serene-seasons-291874:2799213'
    buildDependencies 'curse.maven:fancy-menu-367706:4655936'
    buildDependencies 'curse.maven:konkrete-410295:4514895'
    buildDependencies 'curse.maven:open-terrain-generator-265894:5286210'
    buildDependencies 'curse.maven:custom-main-menu-226406:2857869'
    buildDependencies 'libs:OptifineDeobf:1.12.2-G5'
}

processResources {
    inputs.property('version', mod_stage != "" ? "${mod_version}-${mod_stage}" : "${mod_version}")

    filesMatching('mcmod.info') {
        expand version: inputs.properties.get('version')
    }
}

java {
    withSourcesJar()
}

jar {
    archiveBaseName = mod_name
    archiveAppendix = mc_version
    archiveVersion = mod_version
    archiveClassifier = mod_stage != "" ? mod_stage + '-thin' : 'thin'

    manifest {
        attributes 'FMLAT': 'accesstransformer.cfg'
        attributes 'FMLCorePlugin': "${mod_plugin_class}"
        attributes 'FMLCorePluginContainsFMLMod': 'true'
    }
}

jar.finalizedBy('reobfJar')

shadowJar {
    archiveClassifier = ''

    configurations = [project.configurations.bundled]
}

reobf {
    shadowJar {}
}

shadowJar.finalizedBy('reobfShadowJar')

compileJava {
    classpath = sourceSets.main.compileClasspath + configurations.buildDependencies
}
