# gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.installations.auto-download=false

# gradle plugins
shadow_version=9.2.+

# minecraft
mc_version=1.12.2

# forge
forge_gradle_version=6.0.+
forge_version=14.23.5.2860
mappings_channel=stable
mappings_version=39-1.12

# mod
mod_id=rltweaker
mod_group=com.charles445
mod_name=RLTweaker
mod_version=0.7.5
mod_stage=
mod_plugin_class=com.charles445.rltweaker.asm.RLTweakerPlugin
